from __future__ import annotations

import re
from pathlib import Path

from db_setup import DB_PATH, init_db

# (keyword, category, intent, monthly_volume, difficulty, affiliate_partner)
_SEED: list[tuple[str, str, str, int, int, str | None]] = [
    # ai-writing — comparison
    ("best ai writing tools 2026", "ai-writing", "comparison", 8100, 32, "jasper"),
    ("jasper ai vs writesonic", "ai-writing", "comparison", 2400, 28, "jasper"),
    ("copy ai vs jasper", "ai-writing", "comparison", 1900, 25, "jasper"),
    ("writesonic vs copy ai", "ai-writing", "comparison", 1600, 22, "writesonic"),
    ("best ai copywriting tools", "ai-writing", "comparison", 3200, 33, "jasper"),
    ("surfer seo vs clearscope", "ai-writing", "comparison", 1200, 30, "surfer"),
    (
        "jasper ai vs chatgpt for writing",
        "ai-writing",
        "comparison",
        4400,
        38,
        "jasper",
    ),
    ("ai email writer tools comparison", "ai-writing", "comparison", 2800, 27, None),
    # ai-writing — informational
    ("writesonic review 2026", "ai-writing", "informational", 2200, 30, "writesonic"),
    ("jasper ai review 2026", "ai-writing", "informational", 4400, 35, "jasper"),
    ("copy ai review 2026", "ai-writing", "informational", 1900, 25, None),
    ("surfer seo review 2026", "ai-writing", "informational", 3300, 30, "surfer"),
    (
        "ai writing tools for bloggers",
        "ai-writing",
        "informational",
        2100,
        28,
        "jasper",
    ),
    (
        "best ai tools for content marketing",
        "ai-writing",
        "informational",
        4500,
        40,
        "jasper",
    ),
    # ai-writing — tutorial
    ("how to use jasper ai", "ai-writing", "tutorial", 1800, 20, "jasper"),
    ("how to use surfer seo", "ai-writing", "tutorial", 1100, 22, "surfer"),
    ("how to write seo articles with ai", "ai-writing", "tutorial", 2600, 30, "jasper"),
    # ai-image — comparison
    ("best ai image generators 2026", "ai-image", "comparison", 9200, 38, None),
    ("midjourney vs dall-e 3", "ai-image", "comparison", 5400, 32, None),
    ("stable diffusion vs midjourney", "ai-image", "comparison", 4100, 34, None),
    ("adobe firefly vs midjourney", "ai-image", "comparison", 2200, 30, None),
    ("best ai image upscalers", "ai-image", "comparison", 2400, 22, None),
    # ai-image — informational
    ("midjourney review 2026", "ai-image", "informational", 6600, 40, None),
    ("dall-e 3 review 2026", "ai-image", "informational", 3300, 28, None),
    ("ai art generators for beginners", "ai-image", "informational", 3100, 25, None),
    # ai-image — tutorial
    ("how to use midjourney", "ai-image", "tutorial", 8800, 35, None),
    ("how to create ai art for free", "ai-image", "tutorial", 5500, 30, None),
    ("stable diffusion setup guide", "ai-image", "tutorial", 3200, 28, None),
    # ai-video — comparison
    ("best ai video generators 2026", "ai-video", "comparison", 5500, 35, None),
    ("descript vs riverside", "ai-video", "comparison", 1800, 25, None),
    ("elevenlabs vs murf ai", "ai-video", "comparison", 1600, 24, "elevenlabs"),
    (
        "ai voice cloning tools comparison",
        "ai-video",
        "comparison",
        2900,
        28,
        "elevenlabs",
    ),
    ("best text to video ai tools", "ai-video", "comparison", 4200, 36, None),
    ("synthesia vs heygen", "ai-video", "comparison", 2300, 28, None),
    # ai-video — informational
    ("runway ml review 2026", "ai-video", "informational", 2700, 30, None),
    ("elevenlabs review 2026", "ai-video", "informational", 3900, 32, "elevenlabs"),
    ("descript review 2026", "ai-video", "informational", 2500, 26, None),
    # ai-video — tutorial
    ("how to use descript", "ai-video", "tutorial", 2100, 22, None),
    ("how to make ai videos for youtube", "ai-video", "tutorial", 6100, 33, None),
    (
        "elevenlabs voice cloning tutorial",
        "ai-video",
        "tutorial",
        2200,
        20,
        "elevenlabs",
    ),
    # ai-code — comparison
    ("best ai coding assistants 2026", "ai-code", "comparison", 7200, 37, None),
    ("github copilot vs cursor", "ai-code", "comparison", 4800, 35, None),
    ("tabnine vs github copilot", "ai-code", "comparison", 2200, 28, None),
    ("ai code review tools comparison", "ai-code", "comparison", 3100, 30, None),
    # ai-code — informational
    ("cursor ai review 2026", "ai-code", "informational", 5100, 32, None),
    ("github copilot review 2026", "ai-code", "informational", 4300, 38, None),
    ("codeium review 2026", "ai-code", "informational", 2100, 22, None),
    ("best ai tools for developers 2026", "ai-code", "informational", 4600, 40, None),
    # ai-code — tutorial
    ("how to use github copilot", "ai-code", "tutorial", 5500, 30, None),
    ("how to use cursor ai", "ai-code", "tutorial", 3400, 25, None),
    ("cursor ai setup guide for vscode", "ai-code", "tutorial", 2200, 20, None),
    # ai-productivity — comparison
    (
        "best ai productivity tools 2026",
        "ai-productivity",
        "comparison",
        6600,
        35,
        None,
    ),
    ("notion ai vs chatgpt", "ai-productivity", "comparison", 3200, 30, None),
    (
        "best ai meeting assistants 2026",
        "ai-productivity",
        "comparison",
        3400,
        30,
        None,
    ),
    ("best ai scheduling tools", "ai-productivity", "comparison", 2600, 28, None),
    # ai-productivity — informational
    ("notion ai review 2026", "ai-productivity", "informational", 4800, 33, None),
    ("otter ai review 2026", "ai-productivity", "informational", 2800, 28, None),
    ("reclaim ai review 2026", "ai-productivity", "informational", 1500, 20, None),
    ("ai tools for solopreneurs", "ai-productivity", "informational", 3200, 32, None),
    (
        "zapier ai features explained",
        "ai-productivity",
        "informational",
        2100,
        25,
        None,
    ),
    # ai-productivity — tutorial
    ("how to use notion ai", "ai-productivity", "tutorial", 3500, 25, None),
    ("otter ai setup guide", "ai-productivity", "tutorial", 1200, 18, None),
    # ai-writing — expansion
    ("rytr vs jasper ai", "ai-writing", "comparison", 1400, 24, "jasper"),
    ("anyword vs jasper", "ai-writing", "comparison", 900, 22, "jasper"),
    ("grammarly vs jasper ai", "ai-writing", "comparison", 3600, 36, "jasper"),
    ("best ai paraphrasing tools", "ai-writing", "comparison", 2800, 26, None),
    ("best ai blog writing tools 2026", "ai-writing", "comparison", 2400, 31, "jasper"),
    ("frase vs surfer seo", "ai-writing", "comparison", 1100, 27, "surfer"),
    ("writesonic vs jasper for blogs", "ai-writing", "comparison", 1300, 23, "jasper"),
    ("best ai headline generators", "ai-writing", "comparison", 1600, 21, None),
    ("grammarly ai review 2026", "ai-writing", "informational", 4100, 34, None),
    ("rytr ai review 2026", "ai-writing", "informational", 980, 18, None),
    ("anyword review 2026", "ai-writing", "informational", 720, 19, None),
    (
        "ai writing tools for ecommerce",
        "ai-writing",
        "informational",
        1500,
        28,
        "jasper",
    ),
    (
        "best ai tools for seo content",
        "ai-writing",
        "informational",
        2700,
        33,
        "surfer",
    ),
    ("clearscope review 2026", "ai-writing", "informational", 1400, 29, None),
    ("neuronwriter review 2026", "ai-writing", "informational", 860, 20, None),
    ("ai content detectors explained", "ai-writing", "informational", 2200, 24, None),
    ("how to use writesonic", "ai-writing", "tutorial", 1600, 21, "writesonic"),
    ("how to use grammarly ai", "ai-writing", "tutorial", 2900, 26, None),
    ("how to use copy ai", "ai-writing", "tutorial", 1100, 19, None),
    ("surfer seo content editor tutorial", "ai-writing", "tutorial", 900, 23, "surfer"),
    ("how to humanize ai writing", "ai-writing", "tutorial", 3400, 32, None),
    ("how to fact check ai articles", "ai-writing", "tutorial", 1200, 22, None),
    ("jasper ai brand voice setup guide", "ai-writing", "tutorial", 800, 17, "jasper"),
    # ai-image — expansion
    ("leonardo ai vs midjourney", "ai-image", "comparison", 2800, 30, None),
    ("ideogram vs midjourney", "ai-image", "comparison", 1900, 26, None),
    ("flux ai vs midjourney", "ai-image", "comparison", 2400, 29, None),
    ("best ai logo generators 2026", "ai-image", "comparison", 3100, 28, None),
    ("best ai background removers", "ai-image", "comparison", 2600, 22, None),
    ("photoshop generative fill vs firefly", "ai-image", "comparison", 1700, 31, None),
    ("canva magic studio vs adobe firefly", "ai-image", "comparison", 2100, 27, None),
    ("best ai photo enhancers 2026", "ai-image", "comparison", 1800, 23, None),
    ("krea ai vs midjourney", "ai-image", "comparison", 900, 20, None),
    ("playground ai vs leonardo ai", "ai-image", "comparison", 1100, 21, None),
    ("leonardo ai review 2026", "ai-image", "informational", 2200, 25, None),
    ("ideogram ai review 2026", "ai-image", "informational", 1400, 22, None),
    ("flux ai image review 2026", "ai-image", "informational", 1600, 24, None),
    ("adobe firefly review 2026", "ai-image", "informational", 2500, 30, None),
    (
        "ai image generators for product photos",
        "ai-image",
        "informational",
        1900,
        27,
        None,
    ),
    (
        "best ai tools for graphic design 2026",
        "ai-image",
        "informational",
        3300,
        34,
        None,
    ),
    ("magnific ai review 2026", "ai-image", "informational", 1200, 23, None),
    ("topaz photo ai review 2026", "ai-image", "informational", 1500, 26, None),
    ("ai art copyright explained", "ai-image", "informational", 1800, 21, None),
    ("canva ai image generator review", "ai-image", "informational", 2000, 28, None),
    ("how to use leonardo ai", "ai-image", "tutorial", 1700, 20, None),
    ("how to use adobe firefly", "ai-image", "tutorial", 2100, 24, None),
    ("how to use stable diffusion locally", "ai-image", "tutorial", 2800, 32, None),
    ("how to write midjourney prompts", "ai-image", "tutorial", 4200, 29, None),
    ("how to upscale images with ai", "ai-image", "tutorial", 1900, 22, None),
    ("how to remove backgrounds with ai", "ai-image", "tutorial", 2400, 20, None),
    ("stable diffusion controlnet tutorial", "ai-image", "tutorial", 1300, 27, None),
    ("how to use ideogram for text in images", "ai-image", "tutorial", 1100, 19, None),
    (
        "how to generate consistent ai characters",
        "ai-image",
        "tutorial",
        1600,
        25,
        None,
    ),
    # ai-video — expansion
    ("runway vs pika labs", "ai-video", "comparison", 2100, 28, None),
    (
        "heygen vs synthesia for training videos",
        "ai-video",
        "comparison",
        1400,
        26,
        None,
    ),
    ("kapwing vs descript", "ai-video", "comparison", 980, 22, None),
    ("invideo ai vs pictory", "ai-video", "comparison", 1600, 24, None),
    ("best ai avatar video tools", "ai-video", "comparison", 2300, 30, None),
    ("murf ai vs play ht", "ai-video", "comparison", 900, 21, None),
    ("luma ai vs runway", "ai-video", "comparison", 1800, 27, None),
    ("best ai video editors 2026", "ai-video", "comparison", 2900, 33, None),
    ("opus clip vs vidyo ai", "ai-video", "comparison", 1200, 23, None),
    ("veed io vs descript", "ai-video", "comparison", 1100, 22, None),
    ("heygen review 2026", "ai-video", "informational", 2400, 28, None),
    ("synthesia review 2026", "ai-video", "informational", 2100, 29, None),
    ("pika labs review 2026", "ai-video", "informational", 1700, 24, None),
    ("invideo ai review 2026", "ai-video", "informational", 1500, 23, None),
    ("pictory review 2026", "ai-video", "informational", 1300, 22, None),
    ("murf ai review 2026", "ai-video", "informational", 1400, 25, None),
    ("ai video tools for marketers", "ai-video", "informational", 1900, 31, None),
    ("best ai tools for youtube shorts", "ai-video", "informational", 2600, 30, None),
    ("capcut ai features explained", "ai-video", "informational", 1800, 26, None),
    ("how to use runway ml", "ai-video", "tutorial", 2000, 24, None),
    ("how to use heygen", "ai-video", "tutorial", 1600, 21, None),
    ("how to use synthesia", "ai-video", "tutorial", 1400, 22, None),
    (
        "how to clone your voice with elevenlabs",
        "ai-video",
        "tutorial",
        1800,
        19,
        "elevenlabs",
    ),
    (
        "how to turn blog posts into videos with ai",
        "ai-video",
        "tutorial",
        1500,
        25,
        None,
    ),
    ("pictory tutorial for youtube", "ai-video", "tutorial", 800, 18, None),
    ("how to use pika labs", "ai-video", "tutorial", 1200, 20, None),
    (
        "how to add ai voiceover to videos",
        "ai-video",
        "tutorial",
        1700,
        23,
        "elevenlabs",
    ),
    ("opus clip tutorial for short form video", "ai-video", "tutorial", 900, 19, None),
    # ai-code — expansion
    ("cursor vs windsurf", "ai-code", "comparison", 3200, 30, None),
    ("claude code vs cursor", "ai-code", "comparison", 2800, 33, None),
    ("github copilot vs codeium", "ai-code", "comparison", 1900, 27, None),
    ("cody vs github copilot", "ai-code", "comparison", 1100, 24, None),
    ("best ai tools for code refactoring", "ai-code", "comparison", 1400, 26, None),
    ("amazon q developer vs github copilot", "ai-code", "comparison", 1300, 29, None),
    ("continue dev vs cursor", "ai-code", "comparison", 900, 22, None),
    ("best ai pair programming tools", "ai-code", "comparison", 1600, 28, None),
    ("aider vs cursor for coding", "ai-code", "comparison", 800, 21, None),
    ("sourcegraph cody vs cursor", "ai-code", "comparison", 1000, 25, None),
    ("windsurf ai review 2026", "ai-code", "informational", 2400, 28, None),
    ("claude code review 2026", "ai-code", "informational", 3100, 34, None),
    ("amazon q developer review 2026", "ai-code", "informational", 1200, 26, None),
    ("tabnine review 2026", "ai-code", "informational", 1500, 27, None),
    ("best ai tools for debugging code", "ai-code", "informational", 1800, 29, None),
    ("ai coding tools for beginners", "ai-code", "informational", 2200, 24, None),
    ("best free ai coding assistants", "ai-code", "informational", 2700, 31, None),
    ("devin ai review 2026", "ai-code", "informational", 1900, 32, None),
    ("replit agent review 2026", "ai-code", "informational", 1400, 25, None),
    ("ai tools for writing unit tests", "ai-code", "informational", 1600, 23, None),
    ("how to use windsurf ai", "ai-code", "tutorial", 1300, 20, None),
    ("how to use codeium", "ai-code", "tutorial", 1100, 18, None),
    ("github copilot setup guide for vscode", "ai-code", "tutorial", 2400, 22, None),
    ("how to use claude code", "ai-code", "tutorial", 1800, 24, None),
    (
        "how to write better prompts for coding ai",
        "ai-code",
        "tutorial",
        1500,
        21,
        None,
    ),
    ("how to use cursor rules", "ai-code", "tutorial", 900, 17, None),
    ("tabnine setup guide", "ai-code", "tutorial", 700, 16, None),
    ("how to review pull requests with ai", "ai-code", "tutorial", 1200, 23, None),
    ("how to generate unit tests with copilot", "ai-code", "tutorial", 1100, 20, None),
    # ai-productivity — expansion
    ("motion vs reclaim ai", "ai-productivity", "comparison", 1400, 24, None),
    ("clockwise vs reclaim ai", "ai-productivity", "comparison", 800, 20, None),
    ("fireflies ai vs otter", "ai-productivity", "comparison", 1600, 25, None),
    ("fathom vs otter ai", "ai-productivity", "comparison", 1200, 22, None),
    ("mem ai vs notion ai", "ai-productivity", "comparison", 900, 23, "notion"),
    ("best ai note taking apps 2026", "ai-productivity", "comparison", 2800, 30, None),
    ("best ai email assistants 2026", "ai-productivity", "comparison", 2100, 28, None),
    ("superhuman vs shortwave", "ai-productivity", "comparison", 1100, 26, None),
    ("clickup ai vs notion ai", "ai-productivity", "comparison", 1500, 27, "notion"),
    ("todoist ai vs motion", "ai-productivity", "comparison", 700, 19, None),
    ("motion app review 2026", "ai-productivity", "informational", 1300, 24, None),
    ("fireflies ai review 2026", "ai-productivity", "informational", 1700, 26, None),
    ("fathom ai review 2026", "ai-productivity", "informational", 1100, 21, None),
    ("mem ai review 2026", "ai-productivity", "informational", 800, 20, "notion"),
    ("clickup ai review 2026", "ai-productivity", "informational", 1400, 25, None),
    ("ai tools for remote teams", "ai-productivity", "informational", 1900, 29, None),
    (
        "best ai tools for project management",
        "ai-productivity",
        "informational",
        2400,
        32,
        None,
    ),
    ("gamma app review 2026", "ai-productivity", "informational", 1600, 23, None),
    ("beautiful ai review 2026", "ai-productivity", "informational", 900, 22, None),
    ("ai tools for meeting notes", "ai-productivity", "informational", 1800, 24, None),
    ("how to use otter ai", "ai-productivity", "tutorial", 1500, 18, None),
    ("how to use motion app", "ai-productivity", "tutorial", 900, 17, None),
    ("how to use fireflies ai", "ai-productivity", "tutorial", 1000, 19, None),
    ("reclaim ai setup guide", "ai-productivity", "tutorial", 700, 16, None),
    (
        "how to automate tasks with zapier ai",
        "ai-productivity",
        "tutorial",
        1600,
        24,
        None,
    ),
    (
        "how to use notion ai for meeting notes",
        "ai-productivity",
        "tutorial",
        1300,
        21,
        "notion",
    ),
    (
        "how to build a second brain with notion ai",
        "ai-productivity",
        "tutorial",
        1800,
        26,
        "notion",
    ),
    (
        "gamma app tutorial for presentations",
        "ai-productivity",
        "tutorial",
        1100,
        20,
        None,
    ),
    (
        "how to summarize meetings with ai",
        "ai-productivity",
        "tutorial",
        2000,
        23,
        None,
    ),
]


def _to_slug(keyword: str) -> str:
    slug = keyword.lower()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"\s+", "-", slug.strip())
    return slug


def seed(db_path: Path = DB_PATH) -> int:
    conn = init_db(db_path)
    rows = [
        (kw, cat, intent, vol, diff, _to_slug(kw), partner)
        for kw, cat, intent, vol, diff, partner in _SEED
    ]
    conn.executemany(
        """
        INSERT OR IGNORE INTO keywords
            (keyword, category, intent, monthly_volume, difficulty, slug, affiliate_partner)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        rows,
    )
    conn.commit()
    inserted = conn.execute("SELECT COUNT(*) FROM keywords").fetchone()[0]
    conn.close()
    return inserted


if __name__ == "__main__":
    count = seed()
    print(f"seed_complete rows={count}")
